### ISSUE TITLE
Inclusion of foundational Symbolic Execution research

### ISSUE THREAD

**Issue by zv** [enzet/symbolic-execution#12]
Some extend the honor of "first" to a symbolic execution program called [EFFIGY (1976) ](http://madhu.cs.illinois.edu/cs598-fall10/king76symbolicexecution.pdf). Others acknowledge a program called [SELECT (1976)](http://lieanu.github.io/papers/se/select75.pdf).

Both would be great additions who also contain bibliographies with lots of references to earlier work in program verification (most notably the verification of avionics in the United States Air Force - a kind of proto-cyberwarfare fear that the Russians, known for their technical prowess, could "hack" airplanes).

It's unclear how you might combine more modern innovations like "VSIDS", but it would be fantastic to see such a thing as well.

Thanks for putting this together!!

**Comment by enzet** [comment]
_Symbolic Execution and Program Testing_ by J. C. King is already on the diagram. And I don't know how could I have missed SELECT paper. I should definitely add it and better investigate their bibliographies.

As for VSIDS, I'm not pretty familiar with it and need some time for research.

Thanks a lot for the suggestions! And special thanks for the “technical prowess” from Russian :-)

**Comment by zv** [comment]
I didn't even see the reference to the EFFIGY paper, thank you!

**Comment by enzet** [comment]
Add _A System to Generate Test Data and Symbolically Execute Programs_.

**Comment by enzet** [comment]
@zhangysh1995 Why confused emoji?
